services:
  db:
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    container_name: 'tiki_backend'
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'
    networks:
      - tiki_network

  redis:
    image: redis:7.2-alpine
    ports:
      - '6379:6379'
    container_name: 'tiki_redis'
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - tiki_network

volumes:
  mysql_data:
  elasticsearch_data:
  redis_data:

networks:
  tiki_network:
