export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password/',
  PROFILE: '/profile',
  PRODUCT: '/product/:slug/:productId',
  SEARCH: '/search',
  CART: '/cart',
  CHECKOUT: '/checkout',
  CHECKOUT_SHIPPING: '/checkout/shipping',
  ADMIN_HOME: '/admin',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_REGISTER: '/admin/register',
  ADMIN_USERS: '/admin/users',
  ADMIN_CREATE_USER: '/admin/create-user',
  ADMIN_EDIT_USER: '/admin/users/:userId',
  ADMIN_DETAIL_USER: '/admin/users/details/:userId',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_PRODUCTS_CREATE: '/admin/product/create',
  ADMIN_EDIT_PRODUCT: '/admin/products/:productId',
  ADMIN_ORDER: '/admin/orders',
  ADMIN_ACCOUNT: '/admin/account',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_SHOPS: '/admin/shops',
  ADMIN_SHOPS_CREATE: '/admin/shops/create',
  ADMIN_FORGOT_PASSWORD: '/admin/forgot-password',
  ADMIN_RESET_PASSWORD: '/admin/reset-password',
  CONTACT: '/contact',
  PAYMENT: '/payment',

  NOTIFICATIONS: '/notifications',
  ACCOUNT: '/account',
  ACCOUNT_INFO: '/account/info',
  ACCOUNT_ORDERS: '/account/orders',
  ACCOUNT_RETURNS: '/account/returns',
  ACCOUNT_ADDRESS: '/account/address',
  ACCOUNT_PAYMENTS: '/account/payments',
  ACCOUNT_REVIEWS: '/account/reviews',
  ACCOUNT_VIEWED: '/account/viewed',
  ACCOUNT_FAVORITES: '/account/favorites',
  ACCOUNT_COMMENTS: '/account/comments',
  ACCOUNT_SUPPORT: '/account/support',

  ADMIN_NOT_FOUND_404: '/not-found-404',
  NOT_FOUND_404: '/404',
} as const;
